name: Tests: R

on:
  push:
    branches: [main, release]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron:  '0 1 * * 1'


jobs:
  Library:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        R: [ '3.5.3', '4.1' ]
    name: R ${{ matrix.R }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.0' # The R version to download (if necessary) and use.
      - run: Rscript -e 'print("hello")'
