name: Tests R

on:
  push:
    branches: [main, release]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron:  '2 3 * * 4'


jobs:
  Library:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        r-version: ['3.6', '4.2']
        python-version: ['3.9']
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install depends
        run: |
          Rscript -e "install.packages(c('remotes','reticulate'))"
      - name: Test R
        run: |
          Rscript tests/R/test_classification.R
          Rscript tests/R/test_regression.R
