name: Tests R

on:
  push:
    branches: [main, release]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron:  '0 1 * * 1'


jobs:
  Library:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        r-version: ['3.6', '4.1', "4.2"]
        python-version: ['3.7', '3.8', '3.9', "3.10"]
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: setup r-reticulate venv
        shell: Rscript {0}
        run: |
          remotes::install_local()
          reticulate::virtualenv_create("r-reticulate", Sys.which("python"))
          reticulate::virtualenv_install("r-reticulate",
            c("docutils", "pandas", "scipy", "matplotlib", "ipython",
              "tabulate", "plotly", "psutil", "kaleido"))
          python <- reticulate::virtualenv_python("r-reticulate")
          writeLines(sprintf("RETICULATE_PYTHON=%s", python),
                     Sys.getenv("GITHUB_ENV"))
      - name: Test R
        run: |
          Rscript tests/R/test_classification.R
