name: Tests R

on:
  push:
    branches: [main, release]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron:  '0 1 * * 1'


jobs:
  Library:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        r-version: ['3.6', '4.1', "4.2"]
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install Miniconda
        run: |
          Rscript -e "remotes::install_github('rstudio/reticulate')"
          Rscript -e "reticulate::install_miniconda()"
      - if: runner.os == 'macOS'
        run: echo "options(reticulate.conda_binary = reticulate:::miniconda_conda())" >> .Rprofile
      - name: Test R
        run: |
          Rscript tests/R/test_classification.R
